### ISSUE TITLE
SMS verification not supported by play store.

### ISSUE THREAD

**Issue by rajam1215** [swarajsaaj/otpReader#19]
Hello

Play store now restrict the SMS or call log permission, this library is useless if play store not approve app with automatic OTP reader functionality in app.

Please give some solution
Thanks

**Comment by swarajsaaj** [comment]
@rajam1215 Due to recent change in permission policy, this is no more useful, I am looking for alternative API

**Comment by rajam1215** [comment]
@swarajsaaj 
Hello

please give some solution for new api of google , many example are there in GitHub with sms api of google, but i want documentation from you, because your documentation is very easy to understand and implementation is very good, i appriciate, please solve that soon

Thanks
