### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by ritesh94** [swarajsaaj/otpReader#3]
Will it support android 23 and above versions ?

**Comment by swarajsaaj** [comment]
@ritesh94  Hi Ritesh, It supports android 23 (Marshmallow) as of now. I have plans to test and upgrade it on future versions too.

**Comment by ritesh94** [comment]
Thanks Swarajsaaj,  it's working on 23. Upgrading for future versions would be great... !!

**Comment by hpatel4u** [comment]
Hi Just to confirm, do we need to give ready below permission or how for API lvl 23+?

    <uses-permission android:name="android.permission.RECEIVE_SMS" />
    <uses-permission android:name="android.permission.READ_SMS" />

**Comment by ritesh94** [comment]
No different permissions to be given for API 23+ 

Just following permissions as mentioned works..............

 <uses-permission android:name="android.permission.RECEIVE_SMS" />
    <uses-permission android:name="android.permission.READ_SMS" />

**Comment by swarajsaaj** [comment]
Closing issue as it is related to Permissions.
