### ISSUE TITLE
How to unregister recieving sms?

### ISSUE THREAD

**Issue by shailendrapundhir** [swarajsaaj/otpReader#6]
Was just curious how to unregister the otpReader to stop reading sms after a time, in case activity remains open in the background? I know this should not have been added in issues because its not, the library in itself is fantastic, but I had no other means to ask questions regarding the library.

**Comment by swarajsaaj** [comment]
I think it was same as https://github.com/swarajsaaj/otpReader/issues/5 . Let me know if your question was something else
