### ISSUE TITLE
When multiple OTP come that time app crash

### ISSUE THREAD

**Issue by rajam1215** [swarajsaaj/otpReader#8]
Crash come when two SMS come at a time. SMS receiver did not handle two SMS at single time. howto solve it can u tell me.

**Comment by swarajsaaj** [comment]
@rajam1215 Can you share your OTPListener implementation and/or the exception trace? because on receiving the message, the callback of listener is called, maybe the listener has something that may be causing the issue?

**Comment by rajam1215** [comment]
This is implements OTPListener and the binder is OtpReader.bind(this, "STDCRP");  STDCRP is my number or address.

OtpReader.bind(this, "STDCRP"); .....................i use in inside oncreate() methoad.

and override methoad outside oncreate() method.

    @Override
    public void otpReceived(String smsText) {
        //Do whatever you want to do with the text
        try {
            String output = smsText.replaceAll("\\s", "");
            String numberOnly = output.replaceAll("[^0-9]", "");
            otp.setText(numberOnly);
            confirm.performClick();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

And this is the receive method 

I use that according your documentation but i steel have error. they come very few times. so error log was not capture. can you give me solution

**Comment by swarajsaaj** [comment]
@rajam1215 I see "confirm.performClick();" being performed on each message receive. There is a chance on second message, that element is destroyed and hence the crash. In next version there is a pull request that allows to unbind listener at wish, till then you may try to bind a null listener after your work is finished.
